# Generated by Django 4.2.25 on 2026-08-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='store',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo de contacto'),
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='store',
            name='receipt_message',
            field=models.TextField(blank=True, help_text='Mensaje que aparece al final de los tickets de compra.', verbose_name='Mensaje de ticket'),
        ),
    ]
