# Generated by Django 4.2.25 on 2026-08-11 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, verbose_name='Nombre de la tienda')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium Status')),
                ('max_products', models.IntegerField(default=50, verbose_name='Límite de productos')),
                ('max_users', models.IntegerField(default=2, verbose_name='Límite de usuarios')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Tienda',
                'verbose_name_plural': 'Perfiles de Tienda',
            },
        ),
    ]
