# Generated by Django 4.2.25 on 2026-08-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_store_address_store_email_store_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_setup_complete',
            field=models.BooleanField(default=False, verbose_name='Configuración completa'),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Debe cambiar contraseña'),
        ),
    ]
