# Generated by Django 4.2.25 on 2026-09-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_store_is_setup_complete_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='max_products',
            field=models.IntegerField(default=500, verbose_name='Límite de productos'),
        ),
        migrations.AlterField(
            model_name='store',
            name='max_users',
            field=models.IntegerField(default=4, verbose_name='Límite de usuarios'),
        ),
    ]
