# Generated by Django 5.2.7 on 2025-10-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='type',
            field=models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida'), ('loss', 'Pérdida')], max_length=4),
        ),
    ]
