# Generated by Django 4.2.25 on 2026-08-17 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_store_is_setup_complete_user_must_change_password'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('store', 'sku')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
    ]
